.TH gtkollection 1 "2012-08-07"
.SH NAME
gtkollection - An application to manage all kind of collections.
.SH SYNOPSIS
gtkollection [\fIOPTIONS\fR]
.SH DESCRIPTION
.B gtkollection
lets you create and manipulate all kind of collections. You can customize the fields
from each collection you create.

.SH AUTHOR
Written by Rodrigo Freitas.

.SH REPORTING BUGS
Report gtkollection bugs through the project page (http://github.com/rsfreitas/gtkollection).

.SH COPYRIGHT
Copyright (c) 2012 Rodrigo Freitas
